name: Update Stock
on:
  workflow_dispatch:
    inputs:
      product:
        description: 'The product to update stock for'
        required: true

jobs:
  update-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load Stock Data
        id: load-stock
        run: |
          PRODUCT="${{ github.event.inputs.product }}"
          STOCK_FILE="stock.json"

          # Read stock.json and update stock
          STOCK=$(jq --arg product "$PRODUCT" '.[$product] -= 1' "$STOCK_FILE")

          # Save updated stock
          echo "$STOCK" > "$STOCK_FILE"

      - name: Commit and Push Stock Update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add stock.json
          git commit -m "Update stock for ${{ github.event.inputs.product }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
