name: Update Stock on Purchase

on:
  repository_dispatch:
    types: [purchase_made]

jobs:
  update_stock:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update Stock Data
      run: |
        echo "Updating stock..."
        PRODUCT_FILE="stock.json"
        STOCK=$(jq '.products["Paramotor LED Kit"].stock -= 1' $PRODUCT_FILE)
        echo "$STOCK" > $PRODUCT_FILE

    - name: Commit and Push Changes
      env:
        MY_TOKEN: ${{ secrets.MY_TOKEN }}  # ✅ Use your custom secret name
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add stock.json
        git commit -m "Updated stock after purchase"
        git push https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME.git
